/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ExamplePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var ExamplePlugin = class extends import_obsidian.Plugin {
  async onload() {
    this.registerMarkdownCodeBlockProcessor("sketch-pen", (src, el) => {
      const div = el.createEl(`div`);
      const cnv = div.createEl(`canvas`);
      const AsyncFunction = async function() {
      }.constructor;
      const run = AsyncFunction(`cnv`, src);
      setTimeout(run, 200, cnv);
    });
  }
};
//# sourceMappingURL=data:application/json;base64,ewogICJ2ZXJzaW9uIjogMywKICAic291cmNlcyI6IFsibWFpbi50cyJdLAogICJzb3VyY2VzQ29udGVudCI6IFsiaW1wb3J0IHsgUGx1Z2luIH0gZnJvbSBcIm9ic2lkaWFuXCJcblxuZXhwb3J0IGRlZmF1bHQgY2xhc3MgRXhhbXBsZVBsdWdpbiBleHRlbmRzIFBsdWdpbiB7XG4gIGFzeW5jIG9ubG9hZCAoKSB7XG4gICAgdGhpcy5yZWdpc3Rlck1hcmtkb3duQ29kZUJsb2NrUHJvY2Vzc29yIChcInNrZXRjaC1wZW5cIiwgKHNyYywgZWwpID0+IHtcblx0XHRjb25zdCBkaXYgPSBlbC5jcmVhdGVFbCAoYGRpdmApXG5cdFx0Y29uc3QgY252ID0gZGl2LmNyZWF0ZUVsIChgY2FudmFzYClcblx0XHRjb25zdCBBc3luY0Z1bmN0aW9uID0gYXN5bmMgZnVuY3Rpb24gKCkge30uY29uc3RydWN0b3Jcblx0XHRjb25zdCBydW4gPSBBc3luY0Z1bmN0aW9uIChgY252YCwgc3JjKVxuXHRcdHNldFRpbWVvdXQgKHJ1biwgMjAwLCBjbnYpXG5cdH0pXG4gIH1cbn0iXSwKICAibWFwcGluZ3MiOiAiOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7QUFBQTtBQUFBO0FBQUE7QUFBQTtBQUFBO0FBQUEsc0JBQXVCO0FBRXZCLElBQXFCLGdCQUFyQixjQUEyQyx1QkFBTztBQUFBLEVBQ2hELE1BQU0sU0FBVTtBQUNkLFNBQUssbUNBQW9DLGNBQWMsQ0FBQyxLQUFLLE9BQU87QUFDdEUsWUFBTSxNQUFNLEdBQUcsU0FBVSxLQUFLO0FBQzlCLFlBQU0sTUFBTSxJQUFJLFNBQVUsUUFBUTtBQUNsQyxZQUFNLGdCQUFnQixpQkFBa0I7QUFBQSxNQUFDLEVBQUU7QUFDM0MsWUFBTSxNQUFNLGNBQWUsT0FBTyxHQUFHO0FBQ3JDLGlCQUFZLEtBQUssS0FBSyxHQUFHO0FBQUEsSUFDMUIsQ0FBQztBQUFBLEVBQ0E7QUFDRjsiLAogICJuYW1lcyI6IFtdCn0K
